package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import org.jinouts.xml.namespace.QName;
import org.jinouts.xml.ws.WebEndpoint;
import org.jinouts.xml.ws.WebServiceClient;
import org.jinouts.xml.ws.WebServiceFeature;
import org.jinouts.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-10-29T19:36:31.978+02:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "WebService1", 
                  wsdlLocation = "http://www.groupbattle.com/webservice1.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class WebService1 extends org.jinouts.ws.JinosService {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "WebService1");
    public final static QName WebService1Soap = new QName("http://tempuri.org/", "WebService1Soap");
    public final static QName WebService1Soap12 = new QName("http://tempuri.org/", "WebService1Soap12");
    public final static QName WebService1HttpPost = new QName("http://tempuri.org/", "WebService1HttpPost");
    public final static QName WebService1HttpGet = new QName("http://tempuri.org/", "WebService1HttpGet");
    static {
        URL url = null;
        try {
            url = new URL("http://www.groupbattle.com/webservice1.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebService1.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.groupbattle.com/webservice1.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebService1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebService1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebService1() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WebService1Soap
     */
    @WebEndpoint(name = "WebService1Soap")
    public WebService1Soap getWebService1Soap() {
        return super.getPort(WebService1Soap, WebService1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService1Soap
     */
    @WebEndpoint(name = "WebService1Soap")
    public WebService1Soap getWebService1Soap(WebServiceFeature... features) {
        return super.getPort(WebService1Soap, WebService1Soap.class, features);
    }
    /**
     *
     * @return
     *     returns WebService1Soap
     */
    @WebEndpoint(name = "WebService1Soap12")
    public WebService1Soap getWebService1Soap12() {
        return super.getPort(WebService1Soap12, WebService1Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService1Soap
     */
    @WebEndpoint(name = "WebService1Soap12")
    public WebService1Soap getWebService1Soap12(WebServiceFeature... features) {
        return super.getPort(WebService1Soap12, WebService1Soap.class, features);
    }
    /**
     *
     * @return
     *     returns WebService1HttpPost
     */
    @WebEndpoint(name = "WebService1HttpPost")
    public WebService1HttpPost getWebService1HttpPost() {
        return super.getPort(WebService1HttpPost, WebService1HttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService1HttpPost
     */
    @WebEndpoint(name = "WebService1HttpPost")
    public WebService1HttpPost getWebService1HttpPost(WebServiceFeature... features) {
        return super.getPort(WebService1HttpPost, WebService1HttpPost.class, features);
    }
    /**
     *
     * @return
     *     returns WebService1HttpGet
     */
    @WebEndpoint(name = "WebService1HttpGet")
    public WebService1HttpGet getWebService1HttpGet() {
        return super.getPort(WebService1HttpGet, WebService1HttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebService1HttpGet
     */
    @WebEndpoint(name = "WebService1HttpGet")
    public WebService1HttpGet getWebService1HttpGet(WebServiceFeature... features) {
        return super.getPort(WebService1HttpGet, WebService1HttpGet.class, features);
    }

}
